var answer_data = {
    Red: "MÀU ĐỎ\na. Ưu điểm\n\
    \n- Về cá nhân: Thái độ tích cực và lạc quan cao độ. Yêu bản thân, dễ dàng đón nhận người khác. Coi cuộc sống như một trải nghiệm đáng để tận hưởng. Yêu thích sự mới mẻ, sự thay đổi và sự sôi động. Luôn vui vẻ, cảm xúc phong phú, dễ bộc lộ ra bên ngoài. Tự do tự tại, không thích bị ràng buộc. Thích đùa giỡn, thích nổi bật và khác biệt. Năng lực biểu hiện mạnh, rất dễ được mọi người yêu thích và chào đón. Nhanh nhẹn hoạt bát, tính hiếu kỳ mạnh.\
    \n- Đặc điểm giao tiếp: Tư duy nhanh nhạy, diễn đạt tốt. Thích thể hiện sự thân mật thông qua tiếp xúc cơ thể. Dễ nói chuyện với mọi người, càng đông càng thấy vui. Khi có mâu thuẫn, sẽ trực tiếp lên tiếng. Là một bậc thầy về diễn thuyết và biểu diễn trên sân khấu. Rất vui khi được bày tỏ ý kiến ​​của mình.\
    \n- Với bạn bè: Chân thành, chủ động và nhiệt tình. Thích kết bạn, giỏi giao tiếp với người lạ. Hài hước, mang đến sự vui vẻ cho bạn bè. Vị tha, có sức hút, thích giúp người, dám nhận lỗi. Thích nhận được sự khẳng định và khen ngợi từ người khác.\
    \n- Về công việc và sự nghiệp: Chủ động trong công việc, tự tìm kiếm nhiệm vụ mới. Có thể thuyết phục được người khác, kích thích sự nhiệt tình hợp tác và tinh thần dám nghĩ dám làm của cả nhóm, coi trọng cảm giác làm việc nhóm. Khiến đối tác dễ chịu. Cực kỳ bùng nổ khi hoàn thành các mục tiêu ngắn hạn. Tin tưởng người khác, giỏi trong việc khen ngợi và khích lệ người khác. Không thích bị quá nhiều quy tắc ràng buột, là người sáng tạo, nhanh nhẹn và hoạt bát trong công việc.\
    \n\
    \nb. Nhược điểm\
    \n- Về cá nhân: Tâm trạng thay đổi thất thường, liều lĩnh, bốc đồng, cả tin. Tính cách mạnh mẽ, không muốn chịu đựng gian khổ, ham muốn hưởng thụ. Thích đi đường tắt, không thể kiên trì. Bất cẩn, vô tổ chức. Không muốn chịu trách nhiệm, mong đợi người khác chịu trách nhiệm thay mình. Dễ dàng để tha thứ cho bản thân và không rút ra được bài học cho mình. Không chịu trưởng thành. Thường buông thả để xoa dịu nỗi đau và những rắc rối của bản thân mà không suy nghĩ nghiêm túc về bản chất của cuộc sống.\
    \n- Đặc điểm giao tiếp: Nói không suy nghĩ, đôi lúc nói đùa về những chuyện nghiêm trọng và nhạy cảm. Thích thể hiện bản thân, hay cướp lời người khác. Dễ mất tập trung, nhanh quên, hứa không giữ lời. Không giữ được bí mật. Không đáng tin cậy, chỉ nói mà không làm. Thích khoe khoang về thành công của mình.\
    \n- Với bạn bè: Thiếu chừng mực, đùa giỡn qua trớn. Chỉ muốn trở thành nhân vật chính, chỉ thích nói về những chủ đề mà mình quan tâm, những chủ đề không liên quan đến mình thì phớt lờ. Chen ngang, làm gián đoạn cuộc trò chuyện của người khác. Những người bạn cũ thường bị lãng quên. Có tính dựa dẫm, mong manh và không thể tự lập.\
    \n- Về công việc và sự nghiệp: Tần suất nhảy việc cao, hay đứng núi này trông núi nọ. Không có kế hoạch, tính cách tùy hứng. Không có trọng tâm, năng lượng dễ bị phân tán, dễ bị mất tập trung. Đánh giá quá cao khả năng của mình. Luôn cảm thấy không cần phải chuẩn bị cho tương lai. Không sẵn sàng dành nhiều sức lực làm việc chăm chỉ để có được vinh quang cao hơn. Suy nghĩ không thực tế, mong đợi mọi công việc đều vui vẻ.\
    ",
    Blue: "MÀU XANH DƯƠNG\na. Ưu điểm\
    \n- Về cá nhân: Triết lý sống nghiêm túc, suy nghĩ sâu sắc, độc lập và không mù quáng chạy theo số đông. Trầm lặng ít nói, trưởng thành. Coi trọng lời hứa, đáng tin cậy, hay giấu kín tài năng. Tuân thủ nguyên tắc, có tinh thần trách nhiệm cao, gọn gàng ngăn nắp. Sâu sắc, sống có mục tiêu và lý tưởng. Nhạy cảm, tinh tế, luôn đặt tiêu chuẩn cao, theo đuổi sự hoàn hảo. Khiêm tốn thận trọng, giỏi phân tích, làm việc có tổ chức và kỷ luật. Đối xử chân thành với mọi người, giàu lòng hy sinh. Suy nghĩ tinh tế, kiên định.\
    \n- Đặc điểm giao tiếp: Thích giao tiếp, nhạy cảm và sâu sắc. Luôn đặt mình vào vị trí của người khác. Có thể ghi nhớ và đồng cảm với những cảm xúc, suy nghĩ của người khác trong cuộc trò chuyện. Thích sự va chạm của các ý tưởng trong trao đổi nhóm. Thường chú ý đến các chi tiết nhỏ của cuộc trò chuyện.\
    \n- bạn bè: Quan tâm người khác một cách thầm lặng, có thể nhớ những ngày đặc biệt. Khi bạn bè gặp khó khăn, luôn cố gắng động viên, an ủi. Hiếm khi bày tỏ suy nghĩ ​​bên trong cho người khác. Thường đóng vai trò giải quyết các vấn đề cần sự phân tích.\
    \n- Về công việc và sự nghiệp: Chú trọng các hệ thống, thủ tục, quy tắc, chi tiết và quy trình. Thường lập kế hoạch trước khi làm điều gì đó và thực hiện theo kế hoạch một cách nghiêm túc. Thích tìm tòi, nghiên cứu dựa trên sự thật. Tận tâm với công việc, theo đuổi sự hoàn mỹ. Tính tự giác cao, thích cách quản lý bằng bảng và số liệu để làm rõ hiệu quả. Coi trọng lời hứa.\
    \n\
    \nb. Nhược điểm\
    \n- Về cá nhân: Cảm xúc ti êu cực cao. Không tin tưởng vào người khác. Quan tâm quá nhiều đến ý kiến ​​và đánh giá của người khác, rất dễ bị ảnh hưởng bởi những đánh giá ti.êu cực. Hay chán nản, bi quan, khó tự giải phóng cảm xúc ti êu cực. Tình cảm mong manh, không kiên định, dễ tủi thân. Hay lo lắng vô cớ, dễ bị tr ầm cảm. Khi thấy người khác thành công một cách dễ dàng, sẽ ghen tị vì nỗ lực của mình không được như những người khác. Khuôn mặt quá u ám, khiến người ta cảm thấy áp lực, khó gần.\
    \n- Đặc điểm giao tiếp: Thường vô thức lên lớp dạy đời người khác. Tính nguyên tắc mạnh mẽ, không dễ thỏa hiệp. Luôn mong muốn người khác có đủ sự nhạy cảm và sâu sắc để thấu hiểu mình. Nghĩ rằng người khác có thể đọc được suy nghĩ của mình. Không chủ động giao tiếp với mọi người. Không thích gây rắc rối cho người khác, cũng không thích người khác gây rắc rối cho mình. Không trung thực và cởi mở khi tiếp xúc với mọi người. Khi làm quen với những người khác hay ở trong trạng thái phòng thủ.\
    \n- Với bạn bè: Quá nhạy cảm và đôi khi khó hòa đồng. Hay có cảm giác bất an mạnh mẽ. Không thích đám đông. Thích phản biện và chỉ trích người khác. Không dễ tha thứ.\
    \n- Đối với công việc và sự nghiệp: Thường đặt kỳ vọng quá cao và không thực tế vào bản thân và người khác. Tính toán quá mức, lo được lo mất, hành động chậm chạp. Hay soi mói người khác. Đánh mất lợi ích lớn vì để ý chuyện nhỏ nhặt, mắc bệnh hình thức. Rất dễ mất ý chí vì kết quả không như ý muốn. Rập khuôn, bảo thủ, giáo điều cứng nhắc, thiếu linh hoạt.",
    Yellow: "MÀU VÀNG\na. Ưu điểm\
    \n- Về cá nhân: Không bao giờ bỏ cuộc, liên tục đặt ra mục tiêu để thúc đẩy bản thân tiến về phía trước. Coi cuộc sống như một cuộc thi. Hành động nhanh nhẹn, tràn đầy năng lượng. Ý chí mạnh mẽ, tự tin, không bị cảm xúc chi phối. Thẳng thắn, dám nghĩ dám làm. Tính cách độc lập, khát khao chiến thắng mãnh liệt. Không sợ cường quyền và dám chấp nhận rủi ro. Không quan tâm đến sự đánh giá của người khác, kiên định với con đường mà mình đã chọn, tự vượt qua khó khăn. Chú ý đến tốc độ và hiệu suất. Dám chấp nhận thử thách và khát khao thành công.\
    \n- Đặc điểm giao tiếp: Thích chi phối toàn bộ cuộc trò chuyện. Có khả năng nắm bắt bản chất của vấn đề. Dùng các từ ngữ ngắn gọn và đi thẳng vào trọng tâm khi nói chuyện, không thích vòng vo.\
    \nVới bạn bè: Đưa ra cách giải quyết vấn đề thay vì chỉ chăm chăm vào chuyện đã xảy ra. Tư vấn, hướng dẫn nhanh chóng, đưa ra lời đề nghị một cách thẳng thắn.\
    \n- Về công việc và sự nghiệp: Hành động nhanh gọn. Có khả năng chịu được căng thẳng cường độ cao trong thời gian dài. Năng lực định hướng mục tiêu mạnh mẽ, giỏi thiết lập mục tiêu. Hướng tới tương lai, có tầm nhìn xa trông rộng. Giỏi trong việc phân chia công việc, luôn kiên trì thúc đẩy công việc đi đến thành công. Có năng lực lãnh đạo bẩm sinh và các kỹ năng tổ chức phong phú. Càng có nhiều sự cạnh tranh thì càng có nghị lực, càng bị kìm hãm thì càng dũng cảm. Tìm kiếm các giải pháp thiết thực, chú trọng vào kết quả và hoàn thành công việc. Đưa ra quyết định nhanh chóng và giải quyết tốt mọi vấn đề gặp phải, có tinh thần trách nhiệm.\
    \n\
    \nb. Nhược điểm\
    \n- Về cá nhân: Không bao giờ nhận sai, kiêu ngạo, độc đoán. Chỉ tập trung vào cảm xúc của riêng mình, không quan tâm đến cảm xúc và suy nghĩ của người khác. Tự cao tự đại, ích kỷ, hống hách, nóng tính, thiếu sự đồng cảm. Thường xuyên kìm nén cảm xúc của mình.\
    \n- Đặc điểm giao tiếp: Thích tranh cãi, nói chuyện đôi khi mang tính công kích. Khó tính, vô cảm, sẵn sàng phản đối những lời phê bình, cố chấp, thiếu kiên nhẫn, không biết lắng nghe. Thái độ gay gắt, nghiêm khắc phê bình người khác, dễ làm cho nhịp độ công việc hoặc cuộc sống của người khác trở nên căng thẳng. Không quen khen người khác. Ham muốn kiểm soát mạnh mẽ, không quan tâm nhiều đến người khác, thiếu lòng khoan dung. Với những người khác nhau thì có cách cư xử khác nhau.\
    \n- Với bạn bè: Không thích tiếp xúc với những người thiếu quyết đoán, yếu đuối. Cố gắng kiểm soát mọi người, mong đợi người khác phục tùng hơn là hợp tác với người khác. Ngoài nội dung công việc, hiếm khi nói về các chủ đề khác. Có thói quen giữ khoảng cách nhất định với mọi người. Rất ít khi quan tâm chân thành trực tiếp đến mọi người. Thích quyết định thay người khác.\
    \n- Về công việc và sự nghiệp: Đắm chìm trong công việc, đặt công việc lên hàng đầu. Coi trọng số lượng hơn chất lượng. Khi không hoàn thành mục tiêu, thì rất dễ nổi nóng và trút giận lên người khác. Thích theo đuổi quyền lực. Vì thể diện mà không chịu khoan nhượng hoặc nhận lỗi. Tập trung quá nhiều vào kết quả mà bỏ qua những điều thú vị trong quá trình làm việc. Tham công tiếc việc, thiếu niềm vui trong cuộc sống. Nóng vội muốn thành công, hay thay đổi.\
    ",
    Green: "MÀU XANH LÁ:\na. Ưu điểm\
    \n- Về cá nhân: Thích yên tĩnh, có sức hút nhẹ nhàng, tính tình ôn hòa, dễ chịu, khiêm tốn. Bản chất tốt bụng, theo đuổi sự hòa hợp trong các mối quan hệ với mọi người. Thích sự bình dị, tính cách điềm tĩnh. Biết hài lòng với những gì mình có, trạng thái tinh thần thoải mái. Thích một cuộc sống đơn giản, hạnh phúc. Dễ thích nghi, hiếm khi nổi giận. Là người nhân hậu, dễ tha thứ cho người khác.\
    \n- Đặc điểm giao tiếp: Lấy nhu thắng cương, thường tránh xung đột và chú trọng vào đôi bên cùng có lợi. Bình tĩnh, hòa nhã, giỏi tiếp thu ý kiến ​​của người khác. Là người kiên nhẫn, biết lắng nghe, có khiếu hài hước và khiến mọi người xung quanh cảm thấy thoải mái. Hào phóng, rộng lượng.\
    \n- Với bạn bè: Hiếm khi gây gổ với mọi người. Nhân ái, biết quan tâm người khác, vị tha, dễ hòa nhập. Là người để bạn bè trút bầu tâm sự. Tôn trọng tính độc lập của người khác, biết cách thu phục lòng người và gắn kết mọi người lại với nhau.\
    \n- Về công việc và sự nghiệp: Có năng lực cân bằng các mối quan hệ. Chịu được áp lực, giải quyết mọi xung đột một cách khéo léo. Chú ý đến quản lý theo định hướng con người, thúc đẩy một môi trường làm việc tích cực. Xử lý công việc một cách tự nhiên, nhẹ nhàng.\
    \n\
    \nb. Nhược điểm\
    \n- Với tư cách cá nhân: Làm việc theo quán tính, không chịu thay đổi, làm ngơ trước những thay đổi của thế giới bên ngoài. Lười biếng, nhát gan, rụt rè, mặc kệ cho người khác bắt nạt mình. Mong đợi sự việc tự động được giải quyết, hoàn toàn ở trong thế bị động, dễ thỏa hiệp, tránh mâu thuẫn. Quan tâm quá nhiều đến phản ứng của người khác mà không dám bày tỏ lập trường và nguyên tắc của bản thân.\
    \n- Đặc điểm giao tiếp: Không đưa ra ý kiến của bản thân mà chuyển áp lực và gánh nặng cho người khác. Không biết cách từ chối người khác, dễ mang đến rắc rối cho bản thân. Hay trốn tránh trách nhiệm.\
    \n- Với bạn bè: Vô trách nhiệm và ba phải. Vì nhún nhường người khác mà kìm nén cảm xúc của chính mình. Mong muốn được lòng mọi người, không trung thực với cảm xúc của bản thân. Dễ mất phương hướng trong cuộc sống. Thiếu đam mê, thờ ơ, lười tham gia bất kỳ hoạt động nào.\
    \n- Về công việc và sự nghiệp: Bằng lòng với hiện tại, không có chí tiến thủ. Hạnh phúc với những điều bình thường, thiếu sáng tạo, sợ rủi ro và thiếu tự tin. Thích trì hoãn, thiếu mục tiêu và ý thức tự giác.\
    "
}

export default answer_data